config/routes.rb
DvdNINJA::Application.routes.draw do

  get "torrents/index"
  resources :movies, only: [:show, :index]

  root to: "movies#index"

  get '/rt', to: 'movies#index', rt: true, as: :rt
  get '/instant', to: 'movies#instant', as: :instant
  get '/queue', to: 'movies#queue', as: :queue
  get '/update_rt', to: 'movies#update_rt', as: :update_rt
  get '/torrent_rt', to: 'movies#torrent_rt', as: :torrent_rt
  get '/download/*url', to: 'movies#download', as: :download

  get '/torrents', to: 'torrents#index', as: :torrents

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def show
    @movie = Movie.find(params[:id])
  end

  def index
    if params[:phrase]
      @movies = Movie.where("title LIKE ?", "%#{params[:phrase]}%").order("release_date DESC")
    else
      @movies = Movie.all.order("release_date DESC").limit(100)
    end

    if params[:rt]
      @movies = @movies.where("rt_id != -1")
    end
  end

  def queue
    if params[:phrase]
      @torrents = Movie.search_pb(params[:phrase])
    end
  end

  def instant
    if params[:phrase]
      @torrents = Movie.queue_magnets(params[:phrase])
    end
  end

  def update_rt
      Movie.update_rt_dvds
      
      redirect_to rt_url
  end

  def torrent_rt
      Movie.torrent_rt_dvds

      redirect_to torrents_url
  end

  def download
    if params[:url]
      Torrent.download(params[:url])
    end

    redirect_to root_url
  end

end

app/helpers/movies_helper.rb
module MoviesHelper

end

app/views/movies/_movie.html.erb
<tr>
  <td><%= movie.title %></td>
  <td><%= movie.studio %></td>
  <td><%= movie.rating %></td>

  <td><%= movie.year %></td>
  <td><%= movie.genre %></td>
  <td><%= movie.release_date %></td>

  <td><%= movie.cover_pic_url %></td>
  <td><%= movie.rt_summary %></td>
  <td><%= movie.critics_score %></td>
  <td><%= movie.users_score %></td>
  <td><%= link_to "Actors", movie.actors %></td>
</tr>

<% if false %>
  <%= movie.actors.each do |a| %>
    <%= render a.first_name %>
    <%= render a.last_name %>
  
  <% end %>

  <%= movie.torrents.each do |t| %>
      <%= render t.magnet_url %>
  <% end %>

  <%= render movie.actors %>

<% end %>

app/views/movies/_torrent.html.erb
<tr>
  <td><%= torrent.title %></td>
  <td><%= link_to "Magnet", download_url(url: torrent.magnet_url) %></td>
</tr>

app/views/movies/index.html.erb
<h1>New movies</h1>

<%= form_tag movies_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :phrase, params[:phrase] %>

    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>


<table border="1">
  <thead>
    <tr>
      <th>Title</th>
      <th>DVD Release Date</th>
      <th>Actor Count</th>
      <th>Torrent Count</th>
      <th>RT</th>
      <th>Torrents</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>

        <% if movie.release_date && Time.now < movie.release_date %>
          <td><b><%= movie.release_date %></b></td>
        <% else %>
          <td><%= movie.release_date %></td>
        <% end %>

        <td><%= movie.actors.count %></td>
        <td><%= movie.torrents.count %></td>
        <td><%= movie.critics_score %>% / <%= movie.users_score %>%</td>
        <td><%= movie.rt_torrents %></td>

        <td><%= link_to 'Show', movie %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/movies/instant.html.erb
<% if @torrents %>
  <h1> ADDED: </h1>

  <%= @torrents.each do |t| %>
    <li><%= t %></li>
  <% end %>

<% end %>


<%= form_tag instant_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :phrase, params[:phrase] %>
    <%= submit_tag "Add", :name => nil %>
  </p>
<% end %>


<%= link_to "Update RT", update_rt_path %>

<%= link_to "Torrent RT", torrent_rt_path %>

app/views/movies/queue.html.erb
<%= form_tag queue_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :phrase, params[:phrase] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>


<% if @torrents %>
  <h1> Found: </h1>

  <table>
    <tbody>
    <%= render partial: 'movies/torrent', collection: @torrents, as: 'torrent' %>
    </tbody>
  </table>

<% end %>

app/views/movies/show.html.erb
<%= render partial: 'movies/torrent', collection: @movie.torrents %>

<%= @movie.actors.each do |a| %>
  <%= a.first_name %> <%= a.last_name %>
<% end %>